e_commerce/e_commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("", include("django.contrib.flatpages.urls")),
]

e_commerce/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.flatpages.sitemaps import FlatPageSitemap
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.views.decorators.cache import cache_page
from django.views.generic.base import TemplateView
from main.sitemap import GoodsViewSitemap

from . import views

sitemaps = {
    "static": FlatPageSitemap,
    "goods": GoodsViewSitemap,
}

urlpatterns = [
    path("", cache_page(60 * 15)(views.index), name="index"),
    path("goods/", views.GoodsList.as_view(), name="goods"),
    path(
        "phone_confirmation/",
        views.PhoneConfirmation.as_view(),
        name="phone-confirmation",
    ),
    path("phone_confirmed/", views.PhoneConfirmed.as_view(), name="phone-confirmed"),
    path("goods/<int:pk>/", views.GoodsDetail.as_view(), name="goods-detail"),
    path(
        "goods/create/",
        views.GoodsCreate.as_view(),
        name="goods-create",
    ),
    path(
        "goods/edit/<int:pk>/",
        views.GoodsUpdate.as_view(),
        name="goods-edit",
    ),
    path(
        "accounts/profile/<int:pk>/",
        views.ProfileUpdate.as_view(),
        name="profile",
    ),
    path("accounts/", include("allauth.urls")),
    path("search/", views.SearchView.as_view(), name="search"),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path(
        "robots.txt",
        TemplateView.as_view(
            template_name="main/robots.txt", content_type="text/plain"
        ),
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

e_commerce/main/models.py
from django.contrib.auth.models import Group, User
from django.contrib.postgres.fields import ArrayField
from django.core.validators import RegexValidator
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from main.tasks import (send_new_goods_subscribers_notification_task,
                        send_welcome_email_task)
from picklefield.fields import PickledObjectField
from sorl.thumbnail import ImageField


class Seller(models.Model):
    """This class describes how to store and operate data about sellers.

    STATUSES - a tuple with possible statuses of a seller that using for
    choice in a status field
    name - a name of a seller
    status - a current status of a seller
    rating - a rating of a seller
    email - a contact email address of a seller
    """

    STATUSES = (
        ("A", "Active"),
        ("P", "Partner"),
        ("T", "Test"),
        ("D", "Disabled"),
    )
    name = models.CharField(max_length=80)
    status = models.CharField(max_length=1, choices=STATUSES, default="A")
    rating = models.FloatField()
    email = models.EmailField(max_length=254)

    def __str__(self) -> str:
        return self.name

    def __repr__(self) -> str:
        return (
            f"Seller(name='{self.name}', status='{self.status}', "
            + f"rating={self.rating}, email='{self.email}')"
        )


class Category(models.Model):
    """This class describes how to store and operate data about a Goods category.

    name - a name of a category
    """

    name = models.CharField(max_length=80)

    def __str__(self) -> str:
        return self.name

    def __repr__(self) -> str:
        return f"Category(name='{self.name}')"


class Tag(models.Model):
    """This class describes how to store and operate data about tags.

    name - a name of a tag
    """

    name = models.CharField(max_length=80, unique=True)

    def __str__(self) -> str:
        return self.name

    def __repr__(self) -> str:
        return f"Tag(name='{self.name}')"


class Goods(models.Model):
    """This class describes how to store and operate data about goods.

    SIZES - a tuple with possible sizes of a good that using for
    choice in a size field
    name - a name of a good
    description - a long text description which will be displayed in
    a detailed view
    seller - foreign key of a seller of this good
    weight - a weight of a good
    category - foreign key of a category of this good
    manufacturer - a manufacturer of this good
    tags - foreign keys of a tags of this good
    size - a size of this good
    rating - a current user's rating of a good
    price - a current price
    discount - a current discount provided by a seller
    image - a photo of this good
    creation_date - a date when a good had been created
    views_counter - a current views counter
    """

    SIZES = (
        ("S", "Small"),
        ("M", "Medium"),
        ("L", "Large"),
    )
    name = models.CharField(max_length=80)
    description = models.TextField()
    seller = models.ForeignKey(
        Seller, on_delete=models.CASCADE, verbose_name="the related seller"
    )
    weight = models.FloatField(null=True, blank=True)
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        verbose_name="the related category",
        null=True,
    )
    manufacturer = models.CharField(max_length=80)
    tags = ArrayField(
        models.CharField(max_length=40, blank=True, null=True), blank=True, null=True
    )
    size = models.CharField(max_length=1, choices=SIZES, null=True, blank=True)
    rating = models.FloatField(default=5.0)
    price = models.FloatField(default=0)
    discount = models.FloatField(default=0, null=False)
    image = ImageField(upload_to="goods/", verbose_name="Фото", blank=True)
    creation_date = models.DateField(verbose_name="Дата создания")
    views_counter = models.IntegerField(default=0)
    in_stock = models.IntegerField(default=0)
    is_published = models.BooleanField(verbose_name="Опубликован", default=True)
    is_archive = models.BooleanField(verbose_name="В архиве", default=False)

    class Meta:
        ordering = ["name"]

    def __str__(self) -> str:
        return self.name

    def __repr__(self) -> str:
        return (
            f"Goods(name='{self.name}', description='{self.description}', "
            + f"seller={self.seller}, weight={self.weight}, "
            + f"category={self.category}, manufacturer='{self.manufacturer}'"
            + f", tags={self.tags}, size='{self.size}', "
            + f"rating={self.rating}, price={self.price}, "
            + f"image={self.image or None})"
        )


class Subscriptions(models.Model):
    """This class describes how to store and operate data about subscriptions.

    name - a name of a subscription
    """

    name = models.CharField(max_length=80)

    def __str__(self) -> str:
        return self.name

    def __repr__(self) -> str:
        return f"Subscriptions(name='{self.name}')"

    @staticmethod
    @receiver(post_save, sender=Goods)
    def goods_add_routine(
        sender: Goods, instance: Goods, created: bool, **kwargs
    ) -> None:
        """This method creates delayed task which sents subscribed users
        an email about a newly created good.

        :param sender: Goods class
        :type sender: class 'main.models.Goods'
        :param instance: a newly created good object
        :type instance: class 'main.models.Goods'
        :param created: a boolean flag which indicates that an object was just
        created
        :type created: bool
        """
        if created:
            subscription = Subscriptions.objects.filter(name="New goods").first()
            if subscription:
                for profile in Profile.objects.filter(subsciber=subscription):
                    send_new_goods_subscribers_notification_task.delay(
                        instance.id, profile.id
                    )


class Profile(models.Model):
    """This class describes how to store and operate data about user's
    profiles.

    user - a foreign key of a user linked to this profile
    phone_regex - a regexp validator for phone number
    phone_number - a phone number for notifications
    is_phone_confirmed - a boolean flag which indicates that a phone number
    was confirmed
    birth_date - a bith date of a user
    avatar - user's uploaded profile pic
    subsciber - a foreign keys of user's subscriptions
    """

    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
    )
    phone_regex = RegexValidator(
        regex=r"^\+?1?\d{9,15}$",
        message="Телефонный номер должен быть в формате: "
        + "'+999999999' и не длиннее 15 символов.",
    )
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True)
    is_phone_confirmed = models.BooleanField(
        default=False, verbose_name="Телефон подтвержден"
    )
    birth_date = models.DateField(null=True, blank=True)
    avatar = ImageField(upload_to="user_profile/", verbose_name="Аватар", blank=True)
    subsciber = models.ManyToManyField(
        Subscriptions, verbose_name="Подписки", blank=True
    )

    def get_absolute_url(self) -> str:
        """This method returns an absolute URL to a user's profile.

        :return: a URL to a user's profile page
        :rtype: str
        """
        return reverse("profile", kwargs={"pk": self.pk})

    @staticmethod
    @receiver(post_save, sender=User)
    def create_user_profile(
        sender: User, instance: User, created: bool, **kwargs
    ) -> None:
        """This method creates a new linked Profile object when
        a user signs up.

        :param sender: User class
        :type sender: class 'django.contrib.auth.models'
        :param instance: a newly created user object
        :type instance: class 'django.contrib.auth.models'
        :param created: a boolean flag which indicates that an object was just
        created
        :type created: bool
        """
        if created:
            common_users_group, created_grp = Group.objects.get_or_create(
                name="common_users"
            )
            instance.groups.add(common_users_group)
            Profile.objects.create(user=instance)
            send_welcome_email_task.delay(instance.id)

    @staticmethod
    @receiver(post_save, sender=User)
    def save_user_profile(sender: User, instance: User, **kwargs) -> None:
        """This method saves a linked Profile object when
        a User object was updated.
        """
        instance.profile.save()


class SMSLog(models.Model):
    """This class describes how to store and operate data about sent messages
    and SMS gate responses.

    user - a foreign key of a user whom SMS was sent
    code - a generated code using for verification
    message - a server response
    creation_date - date and time when a message was sent
    """

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    code = models.PositiveIntegerField()
    message = PickledObjectField()
    creation_date = models.DateTimeField(auto_now_add=True)


class GoodsShort(models.Model):
    """This class describes how to store and operate data about goods.

    name - a name of a good
    description - a long text description which will be displayed in
    a detailed view
    manufacturer - a manufacturer of this good
    tags - foreign keys of a tags of this good
    price - a current price
    creation_date - a date when a good had been created
    views_counter - a current views counter
    """

    class Meta:
        managed = False

    name = models.CharField(max_length=80)
    description = models.TextField()
    manufacturer = models.CharField(max_length=80)
    tags = ArrayField(

e_commerce/main/forms.py
from datetime import date, datetime

from dateutil.relativedelta import relativedelta
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.forms import inlineformset_factory, widgets
from django.utils.translation import gettext as _

from .models import Category, Goods, Profile, SMSLog, Subscriptions, Tag


class UserForm(forms.ModelForm):
    """This class describes a form that used to update a User object's fields."""

    class Meta:
        model = User
        fields = ("first_name", "last_name", "email")
        labels = {
            "first_name": "Имя",
            "last_name": "Фамилия",
            "email": "Email",
        }


class ProfileForm(forms.ModelForm):
    """This class describes a form that used to update
    a Profile object's fields.
    """

    class Meta:
        model = Profile
        fields = "__all__"
        labels = {
            "phone_number": "Телефон",
            "birth_date": "Дата рождения",
            "subsciber": "Подписки",
        }
        widgets = {
            "birth_date": widgets.SelectDateWidget(
                years=range(datetime.now().year - 100, datetime.now().year + 1)
            ),
            "subsciber": widgets.SelectMultiple(choices=Subscriptions.objects.all()),
        }


class GoodsCreateUpdateForm(forms.ModelForm):
    """This class describes a form that used to create a Goods object
    or update an existing Goods object's fields.
    """

    class Meta:
        model = Goods
        fields = (
            "image",
            "name",
            "description",
            "weight",
            "category",
            "manufacturer",
            "tags",
            "size",
            "price",
            "discount",
        )
        labels = {
            "name": "Название",
            "description": "Описание",
            "weight": "Вес",
            "category": "Категория",
            "manufacturer": "Производитель",
            "tags": "Тэги",
            "size": "Размер",
            "price": "Цена",
            "discount": "Скидка",
        }
        widgets = {
            "description": widgets.Textarea(attrs={"cols": 60, "rows": 5}),
            "weight": widgets.NumberInput(),
            "category": widgets.Select(choices=Category.objects.all()),
            "size": widgets.Select(),
            "price": widgets.NumberInput(),
            "discount": widgets.NumberInput(),
        }

    def clean_discount(self):
        """This method provides a custom check for the 'discount' field and
        raises an error if the discount more than 90%.
        """
        data = self.cleaned_data["discount"]
        if data > 90:
            raise ValidationError(
                _("Скидка не может быть больше 90 процентов. " + "Введено: %(value)s"),
                code="invalid",
                params={"value": data},
            )

        return data


class ProfileFormSet(
    inlineformset_factory(User, Profile, form=ProfileForm, can_delete=False)
):
    """This class describes a formset that used to combine the 'UserForm'
    and the 'ProfileForm' in one.
    """

    def __init__(self, *args, **kwargs):
        self.__initial = kwargs.pop("initial", [])
        super(ProfileFormSet, self).__init__(*args, **kwargs)

    def clean(self):
        """This method provides a custom check for the 'birth_date' field and
        raises an error if a user under 18 years old.
        """
        super(ProfileFormSet, self).clean()

        for form in self.forms:
            birth_date = form.cleaned_data.get("birth_date")

            if birth_date:
                today = date.today()
                if (today - relativedelta(years=18)) < birth_date:
                    msg = "Доступ к сайту разрешён лицам старше 18 лет"
                    form.add_error("birth_date", msg)
                    raise ValidationError(
                        _("Too young: %(value)s"),
                        code="invalid",
                        params={"value": birth_date},
                    )


class PhoneConfirmForm(forms.Form):
    """This class describes a form that used to confirm that
    a phone number exists.
    """

    code = forms.IntegerField()

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request", None)
        super(PhoneConfirmForm, self).__init__(*args, **kwargs)

    def clean_code(self):
        """This method provides a custom check for the 'code' field and raises
        an error if an inputted code mismatches a last sent to a user.
        """
        sms_log = (
            SMSLog.objects.filter(user=self.request.user)
            .order_by("creation_date")
            .last()
        )
        code = self.cleaned_data["code"]
        if code != sms_log.code:
            raise ValidationError(
                _("Введён неверный код: %(value)s"),
                code="invalid",
                params={"value": code},
            )
        else:
            profile = Profile.objects.get(user=self.request.user)
            profile.is_phone_confirmed = True
            profile.save()
        return code


class SearchForm(forms.Form):
    """This class describes a form that used for searching goods."""

    search = forms.TextInput()

e_commerce/main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block page_title_header %}
    <title>Bomzhon</title>
    {% endblock %}
    {% load static %}
    <meta name="keywords" content="Магазин, интернет-магазин, товары, купить, цены" />
    <meta name="author" content="GorkyCow" />
    <meta name="copyright" lang="ru" content="Marketplace" />
    {% block meta %}
    {% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
    <script src='https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/js/bootstrap.bundle.min.js'></script>
    <link rel="stylesheet" href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'>
    <link rel="stylesheet" type="text/css" href="{% static 'chat/style.css' %}">
  </head>
  <body>
    {% block header %}
    {% endblock %}
          {% block content %}
          {% endblock %}
          {% include 'chat/room.html' %}
    <footer class="footer">
    </footer>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

e_commerce/main/templates/main/goods_create.html
{% extends request.is_mobile|yesno:"main/mobile_base.html,main/base.html" %}

{% block page_title_header %}<title>Добавление товара</title>{% endblock %}

{% block header %}
        {% include 'main/header.html' with user=user avatar=avatar %}
{% endblock %}

{% block content %}
<main role="main" class="container">
    <div class="starter-template">
        <div class="py-5 text-center">
            <img class="d-block mx-auto mb-4" src="https://getbootstrap.com/docs/4.4/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
            <h2>Добавление товара</h2>
            <p class="lead">Создайте новый товар в нашем магазине</p>
        </div>
        <form class="" novalidate="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% load static %}
            {% load sorl_thumbnail %}
            {% load main_extras %}
            <div class="mb-3">
                {% for field in form %}
                    {% if field.name in filds_for_form_control %}
                        {% if field.errors %}
                            {{ field.label_tag }} {{ field|addclass:'form-control is-invalid' }}
                            <div class="invalid-feedback">
                                {% for error in field.errors %}
                                    {{ error }}
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ field.label_tag }} {{ field|addclass:'form-control' }}
                        {% endif %}
                    {% elif field.name in filds_for_custom_select %}
                        {% if field.errors %}
                            {{ field.label_tag }} {{ field|addclass:'custom-select d-block w-100 is-invalid' }}
                            <div class="invalid-feedback">
                                {% for error in field.errors %}
                                    {{ error }}
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ field.label_tag }} {{ field|addclass:'custom-select d-block w-100' }}
                        {% endif %}
                    {% else %}
                        {% thumbnail goods.image "x148" crop="center" as im %}
                            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                        {% endthumbnail %}
                        <hr class="mb-4">
                        {{ field.label_tag }}
                        {{ field|addclass:'form-control-file' }}
                    {% endif %}
                {% endfor %}
            </div>
            <hr class="mb-4">
            <button class="btn btn-primary btn-lg btn-block" type="submit" value="Update">Сохранить</button>
        </form>
</div>
</main>
{% endblock %}

e_commerce/main/templates/main/goods_detail.html
{% extends request.is_mobile|yesno:"main/mobile_base.html,main/base.html" %}
{% block meta %}
    <meta name="description" content="Описание товарова – интернет-магазина Bomzhon" />
{% endblock %}

{% block page_title_header %}<title>Каталог</title>{% endblock %}

{% block header %}
    {% include 'main/header.html' with user=user avatar=avatar %}
{% endblock %}

{% block content %}
<main role="main" class="container">
  <div class="starter-template">
    {% csrf_token %}
    {% load static %}
    {% load sorl_thumbnail %}
    <div class="card" >
        {% if goods.image %}
          <title>{{ goods.name }}</title>
          {% thumbnail goods.image "x148" crop="center" as im %}
                  <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="card-img-top">
          {% endthumbnail %}
        {% else %}
          <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Future Sale"><title>{{ goods.name }}</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="45%" y="50%" fill="#eceeef" dy=".5em">{{ goods.name }}</text></svg>
        {% endif %}
        <div class="card-body">
          <h5 class="card-title">{{ goods.name }}</h5>
          <p class="card-text">{{ goods.description }}</p>
          <p class="card-text">{{ goods.manufacturer }}</p>
          <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
              <button type="button" class="btn btn-sm btn-outline-secondary">В корзину</button>
              {% if perms.main.change_goods %}
                <button type="button" class="btn btn-sm btn-outline-secondary" onclick="location.href='{% url 'goods-edit' goods.pk %}'">Редактировать</button>
              {% endif %}
            </div>
            <small class="text-muted">
                {% for tag in goods.tags.all %}
                    {{ tag.name }} 
                {% endfor %}
            </small>
          </div>
          <div class="d-flex justify-content-between align-items-center">
            <small class="text-muted">
              Просмотров: {{ views_counter }}
            </small>
          </div>
        </div>
    </div>
  </div>
</main>
{% endblock %}

e_commerce/main/templates/main/goods_list.html
{% extends request.is_mobile|yesno:"main/mobile_base.html,main/base.html" %}

{% block meta %}
    <meta name="description" content="Каталог товаров – интернет-магазина Bomzhon" />
{% endblock %}

{% block page_title_header %}<title>Каталог</title>{% endblock %}

{% block header %}
    {% include 'main/header.html' with user=user avatar=avatar %}
{% endblock %}

{% block content %}
{% load cache %}
<main role="main" class="container">
  <div class="starter-template">
    <div class="container">
        <div class="py-5 text-center">
          <img class="d-block mx-auto mb-4" src="https://getbootstrap.com/docs/4.4/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
          <h2>Каталог</h2>
        </div>

        <div class="d-flex align-items-center p-3 my-3 text-white-50 bg-purple rounded shadow-sm">
          <img class="mr-3" src="https://getbootstrap.com/docs/4.4/assets/brand/bootstrap-outline.svg" alt="" width="48" height="48">
          <div class="lh-100">
            <h6 >Bomzhon. Популярные теги</h6>
            <small>
              {% for tag in tag_list %}
                <a href="{{ request.path }}?tag={{ tag.name }}" class="badge badge-light">{{ tag.name }}</a>
              {% endfor %}
            </small>
          </div>
        </div>

        <div class="row">
        {% if goods_list %}
          {% for goods in goods_list %}
          {% cache 86400 goods_preview goods.id %}
            <div class="col-md-4">
              <div class="card mb-4 shadow-sm">
                <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>{{ goods.name }}</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="40%" y="50%" fill="#eceeef" dy=".3em">{{ goods.name }}</text></svg>
                <div class="card-body">
                  <p class="card-text">{{ goods.description }}</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <button type="button" class="btn btn-sm btn-outline-secondary">В корзину</button>
                      <button type="button" class="btn btn-sm btn-outline-secondary" onclick="location.href='{% url 'goods-detail' goods.pk %}'">Подробнее</button>
                    </div>
                    <small class="text-muted">{{ goods.rating }}</small>
                  </div>
                </div>
              </div>
            </div>
            {% endcache %}
          {% endfor %}
        {% else %}
          <p class="lead">В каталоге пока нет товаров</p>
        {% endif %}
        </div>
      </div>
      {% block pagination %}
        {% if is_paginated %}
          <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">&larr;</a>
                {% endif %}
                <span class="page-current">
                  {% for page_number in page_obj.paginator.page_range %}
                    <a href="{{ request.path }}?page={{ page_number }}" role="button" class="btn btn-sm btn-outline-secondary">{{ page_number }}</a>
                  {% endfor %}
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">&rarr;</a>
                {% endif %}
            </span>
          </div>
        {% endif %}
      {% endblock %} 
  </div>
</main>
{% endblock %}

e_commerce/main/templates/main/phone_confirmation.html
{% extends request.is_mobile|yesno:"main/mobile_base.html,main/base.html" %}

{% block page_title_header %}<title>Вход</title>{% endblock %}

{% block header %}
    {% include 'main/header.html' with user=user avatar=avatar %}
{% endblock %}

{% block content %}
    {% load static %}
    <form class="form-signin" method="POST" action="{% url 'phone-confirmation' %}">
        {% csrf_token %}
        <div class="py-5 text-center">
            <img class="mb-4" src="https://getbootstrap.com/docs/4.4/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
            <h1 class="h3 mb-3 font-weight-normal">Пожалуйста, введите код из SMS</h1>
        </div>
        <input type="number" id="id_code" class="form-control" placeholder="Код из смс" required="" autofocus="" name="code" maxlength="4">
        {% if redirect_field_value %}
        <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
        {% endif %}
        <button class="btn btn-lg btn-primary btn-block" type="submit">Подтвердить</button>
    </form>
    {% if form.errors %}
        <div class="d-flex align-items-center justify-content-center">
            {{ form.errors }}
        </div>
{% endif %}
{% endblock %}

e_commerce/main/templates/main/phone_confirmed.html
{% extends request.is_mobile|yesno:"main/mobile_base.html,main/base.html" %}

{% block page_title_header %}<title>Вход</title>{% endblock %}

{% block header %}
    {% include 'main/header.html' with user=user avatar=avatar %}
{% endblock %}

{% block content %}
    {% load static %}
        {% csrf_token %}
        <div class="py-5 text-center">
            <img class="mb-4" src="https://getbootstrap.com/docs/4.4/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
            <h1 class="h3 mb-3 font-weight-normal">Номер успешно подтвержден!</h1>
        </div>
{% endblock %}